// DO NOT EDIT. This is code generated via package:easy_localization/generate.dart

// ignore_for_file: prefer_single_quotes, avoid_renaming_method_parameters, constant_identifier_names

import 'dart:ui';

import 'package:easy_localization/easy_localization.dart' show AssetLoader;

class CodegenLoader extends AssetLoader{
  const CodegenLoader();

  @override
  Future<Map<String, dynamic>?> load(String path, Locale locale) {
    return Future.value(mapLocales[locale.toString()]);
  }

  static const Map<String,dynamic> _kk_KK = {
  "selectCity": "Қаланы таңдаңыз",
  "allCities": "Барлық қалалар",
  "readMore": "Толығырақ",
  "youCanGetFreeDrink": "Сізге тегін сусын бар!",
  "establishments": "Мекемелер",
  "stock": "Акциялар",
  "toTheRestaurantPage": "Мейрамхана бетіне",
  "viewMenu": "Мәзірді қарау",
  "addressContacts": "Мекен-жайы және байланыстары",
  "allDay": "Тәулік бойы",
  "description": "Сипаттама",
  "profile": "Профиль",
  "myDetails": "Менің деректерім",
  "orderHistory": "Тапсырыс тарихы",
  "paymentMethod": "Төлем әдісі",
  "notifications": "Хабарламалар",
  "support": "Қолдау",
  "language": "Тіл",
  "logOut": "Шығу",
  "bonuses": "бонустар",
  "cashback": "Кэшбэк",
  "myBonuses": "Менің бонустарым",
  "cashbackInPoints": "Кэшбэк ұпайлармен",
  "pointsAccumulated": "Балл жинақталған",
  "bonusHistory": "Бонустар тарихы",
  "howToSpendBonuses": "Бонустарды қалай жұмсауға болады?",
  "howToSpendBonusesDescription": "Sandyq мейрамханаларында немесе tary кофеханаларында сүйікті тағамдарыңызға тапсырыс беріңіз және sandyq Prime қолданбасы арқылы төлеңіз. Төлеу кезінде қанша бонус жұмсағыңыз келетінін таңдаңыз-бонустар тапсырысыңыздың 50% - на дейін жаба алады.",
  "itsOkay": "Түсінікті",
  "points": "ұпай",
  "name": "Аты",
  "telephone": "Телефон",
  "dateOfBirth": "Туған күні",
  "saveChanges": "Өзгерістерді сақтау",
  "deleteAccount": "Есептік жазбаны жою",
  "delete": "Жою",
  "cancel": "Бас тарту",
  "privacyPolicy": "Құпиялылық саясаты",
  "sandyqPrimePublicAgreement": "Қоғамдық шарты",
  "total": "Барлығы",
  "bonusesUpper": "Бонустар",
  "myCards": "Менің карталарым",
  "addCards": "Карта қосу",
  "thereIsNothingHereYet": "Мұнда әлі ештеңе жоқ",
  "nothingHereYetDescription": "Хабарландыру алған кезде ол осында пайда болады",
  "howCanWeHelpYou": "Біз сізге қалай көмектесе аламыз?",
  "textOfTheAppeal": "Өтініш мәтіні",
  "describeTheProblemQuestion": "Мәселені сипаттаңыз немесе сұрақ қойыңыз",
  "additionally": "Қосымша",
  "uploadFile": "Файлды жүктеп алыңыз",
  "send": "Жіберу",
  "areYouAtTaryCoffee": "Сіз Tary кофеханасындасыз ба??",
  "taryCoffeeDescription1": "Өзіңізбен бірге сусынға тапсырыс беру үшін барда QR кодын сканерлеңіз",
  "taryCoffeeDescription2": "Залда сусыннан ләззат алу үшін үстелдегі тақтайшадағы QR кодын сканерлеңіз",
  "scanQRcode": "QR кодын сканерлеңіз",
  "scanQrTable": "Үстелдегі QR сканерін сканерлеңіз",
  "scanQRcodeDescription": "Тапсырыс беру немесе төлеу үшін камераны QR кодына бағыттаңыз",
  "close": "Жабу",
  "chooseFreeDrink": "Тегін сусын таңдаңыз",
  "choose": "Таңдау",
  "order": "Тапсырыс беру",
  "yourOrder": "Сіздің тапсырысыңыз",
  "date": "Күні",
  "restaurantAddress": "Мейрамхана мекен-жайы",
  "orderAmount": "Тапсырыс сомасы",
  "service": "Қызмет көрсету",
  "placeAnOrder": "Тапсырыс беру",
  "totalPrice": "Барлығы",
  "workingHours": "Жұмыс уақыты:",
  "main": "Басты",
  "drinkWaiting": "Сусын сізді күтеді",
  "drinkReceived": "Сусын бүгін алынды",
  "comeBackTomorrow": "Жаңа сусынга ертен оралыңыз!",
  "getFreeDrink": "Сізге тегін сусын бар!",
  "balance": "Баланс",
  "subscriptionInformation": "Жазылым туралы ақпарат",
  "subscription": "Жазылым",
  "active": "Белсенді",
  "benefitsAvailable": "Барлық артықшылықтар сізге қол жетімді",
  "subscriptionActive": "Жазылым белсенді",
  "nextPaymentDate": "Келесі төлем күні",
  "about": "Компания туралы",
  "enterName": "Атын енгізіңіз",
  "enterPhone": "Телефонды енгізіңіз",
  "dateFormat": "кк.аа.жжжж",
  "deleteAccountQuestion": "Есептік жазбаны жойғыңыз келетініне сенімдісіз бе?",
  "status": "Статус",
  "freeDrink": "Тегін сусын",
  "exitAccount": "Есептік жазбадан шығу керек пе?",
  "noBillsPay": "Төлем шоттары жоқ",
  "dishesOrder": "Тапсырыстағы тағамдар",
  "login": "Кіру",
  "youSelectOptions": "Опцияларды таңдау керек: 1 (Міндетті)",
  "learnMore": "Толығырақ",
  "issued": "Ресімделген",
  "arrange": "Ресімдеу",
  "authorization": "Авторизация",
  "yourPhoneNumber": "Сіздің телефон нөміріңіз",
  "getPinCode": "Кодты алу",
  "agreeTerms": "Мен шарттармен келісемін",
  "userAgreement": "Пайдаланушы келісімі",
  "publicContract": "Қоғамдық келісім",
  "enterPinCode": "Кодты енгізіңіз",
  "sentCodeNumber": "Біз нөмірге код жібердік",
  "cont": "Жалғастыру",
  "referralProgram": "Жолдама бағдарламасы",
  "reservations": "Брондау",
  "bonusesForFriend": "Сізге және сіздің досыңызға +1 000 бонус",
  "sendBonuses": "Біз сізге және сіздің досыңызға өтінімдегі бірінші төлемнен кейін әрқайсысына 1000 бонус береміз",
  "sharePromoCode": "Промокодты бөлісіңіз",
  "refProgramConditions": "Реферал бағдарламасының ережелері мен шарттары",
  "bookingDetails": "Брондау мәліметтері",
  "reservationNumber": "Брондау нөмірі",
  "time": "Уақыт",
  "numberOfGuests": "Қонақтар саны",
  "commentForTheRestaurant": "Мейрамхана туралы түсініктеме",
  "cancelBooking": "Брондаудан бас тарту",
  "booking": "Брондау",
  "bookTable": "Үстелге тапсырыс беріңіз",
  "man": "адам.",
  "moreThanSix": "6-дан астам",
  "dateOfVisit": "Барған күні",
  "visitingime": "Келу уақыты",
  "readyToBook": "Тапсырыс беруге дайынсыз ба?",
  "bookNow": "Тапсыру",
  "forExample": "Мысалы: «Мен мекемеде 8 сағат жұмсаймын» немесе «Маған креслолар керек»...",
  "tableReserved": "Үстелге тапсырыс берді",
  "restaurantWillContact": "Брондауыңызға қатысты сұрақтар туындаған жағдайда мейрамхана сізбен хабарласады.",
  "promocodeCopied": "Жарнамалық код көшірілді, оны досыңызбен бөлісіңіз!",
  "freeDrinkWithSubscription": "Жазылымы бар тегін сусын",
  "freedrinksCashback": "Тегін сусындар және 8% кэшбэк",
  "aboutCompany": "Chayla Group мейрамханалар желісі нарықта 5 жылдан бері жұмыс істеп келе жатқан компания болып табылады және қазіргі уақытта желіде 12 жоба бар. Негізгі қызметі: Мейрамхана қызметі және тамақ жеткізу қызметтерін көрсету",
  "subscribeNow": "Қазір жазылыңыз",
  "greatOffer": "15% жеңілдік",
  "coffeLimit": "Сіз бүгін тегін сусынды қолдандыңыз ба?",
  "youCancelledSubscription": "Жазылымнан бас тарттыңыз",
  "subscriptionPaidup": "Жазылым мерзімінен бұрын төленген",
  "afterThisPeriod": "осы кезеңнен кейін барлық PRIME артықшылықтарына қол жеткізу аяқталады",
  "cancelSubscription": "Жазылымнан бас тарту",
  "accessWillEnd": "Тегін сусындар, ұлғайтылған кэшбэк және сыйлықтарға қол жеткізу ақылы кезеңнің соңында аяқталады",
  "yesCancel": "Иә, бас тарту",
  "noLeaveIt": "Жоқ, қалдырыңыз",
  "subscriptionCanceled": "Жазылым тоқтатылды",
  "thanksForUsingPrime": "Prime қолданбасын пайдаланғаныңыз үшін рақмет! Артықшылықтарыңызды қалпына келтіру үшін әрқашан қайта тіркеле аласыз.",
  "workingTime": "Жұмыс уақыты",
  "location": "Орналасқан жері",
  "success": "Сәтті!",
  "closed": "Жабық",
  "invoiceFrom": "Есептік жазба",
  "orderNumber": "Тапсырыс нөмірі",
  "requestSent": "Сіздің сұрауыңыз жіберілді",
  "requestSentDesc": "Мәселе туралы бізге хабарлағаныңыз үшін рақмет!",
  "save": "Сақтау",
  "bonusesHere": "Сіздің бонустарыңыз осында болады",
  "bonusesHereDesc": "Қолданбада тапсырыстар үшін төлеңіз\nжәне 8%-ға дейін кэшбэк алыңыз",
  "ordersHere": "Сіздің тапсырыстарыңыз осында болады",
  "ordersHereDesc": "Қолданбада тапсырыстар үшін төлеңіз және 8% кешбэк алыңыз",
  "pay": "Төлемді жалғастыру",
  "orderAccepted": "Тапсырыс қабылданды!",
  "paymentSuccessful": "Төлем сәтті болды",
  "freeDrinkSuccess": "Қызметкер сусын дайын болған бойда тапсырыс берген жерге әкеледі",
  "orderPaySuccess": "Құттықтаймыз! Тапсырысыңыз төленді",
  "selectPaymentMethod": "Төлем әдісін таңдаңыз",
  "spend": "Жұмсау",
  "spendDescFirst": "Сіз шоттың",
  "spendDescSecond": "дейін төлей аласыз",
  "hasPromoCode": "Сізде промо-код бар ма?",
  "addBonus": "Бонус қосамыз",
  "accumulateBonuses": "Бонус жиналады",
  "apply": "Қолдану",
  "enterPromo": "Жарнамалық кодты енгізіңіз",
  "feedbackSent": "Пікір жіберілді, уақыт бөлгеніңізге рахмет!",
  "commentOptional": "Түсініктеме (міндетті емес)",
  "rateVisitSandyq": "Өз әсеріңізбен бөлісіңіз!",
  "howDidItGo": "Қалай өтті?",
  "site": "Сайт",
  "paymentByQR": "QR арқылы төлеу",
  "gender": "Жыныс",
  "selectGender": "Жынысты таңдаңыз",
  "enterEmail": "Email енгізіңіз",
  "themale": "Ер",
  "thefemale": "Әйел",
  "successSubscriptionPay": "Құттықтаймыз! Сіздің жазылымыңыз рәсімделді.",
  "enterCorrectFormat": "Дұрыс күн пішімін беріңіз",
  "qrNotFound": "Qr код табылмады",
  "qrNotFoundDesc": "Мекеме берген кодты пайдаланып әрекетті қайталаңыз немесе қызметкерден көмек сұраңыз.",
  "whatDoYouWantToDo": "Сіз не істегіңіз келеді?",
  "payOrder": "Тапсырысты төлеу",
  "getAFreeDrink": "Тегін кофе алу",
  "upgradeRequired": "Қосымшаны жаңарту қажет",
  "upgrade": "Жаңарту",
  "more": "Көбірек",
  "additionalRequests": "Мәліметтерді тексеріңіз, егер қосымша тілектер болса, мейрамханаға хабарлаңыз",
  "forExampleAdditional": "Мысалы: «Мекемеде бірнеше сағат боламын», немесе «Балаларға арналған орындықтар керек»...",
  "bookingError": "Брондау қатесі",
  "pleaseTryAgain": "Қайталап көріңіз. Егер қате қайталанса – мейрамханамен байланысыңыз.",
  "detailsNeeded": "Мәліметтерді нақтылау қажет",
  "additionalInformationRestaurant": "Үлкен компанияның келуіне дайындалу үшін қосымша ақпарат қажет. Мейрамханамен байланысыңыз.",
  "call": "Қоңырау шалу",
  "bookingNumber": "Үстел нөмірі",
  "cancelReservationQuestion": "Брондауды болдырмау?",
  "canceled": "Брондау болдырылды",
  "back": "Артқа",
  "noFreeSlots": "Бұл күні брондау үшін бос слоттар жоқ",
  "noActive": "Белсенді броньдар жоқ",
  "noActiveDesc": "Сіз мейрамхананың бетінде алдын ала келуді брондай аласыз",
  "orderError": "Қатесі бар тапсырыс",
  "newOrder": "Жаңа тапсырыс",
  "checkRequested": "Чек сұралды",
  "closedStatus": "Жабық",
  "inProcessing": "Өңделуде",
  "remoteOrder": "Тапсырыс жойылды",
  "accepted": "Қабылданды",
  "canceledStatus": "Болдырылмады",
  "bonusesAccrued": "Бонустар есептелген",
  "leaveFeedback": "Пікір қалдыру",
  "drinkGift": "Сыйлық ретінде",
  "congratulations": "Құттықтаймыз!",
  "successfullyLogged": "Сіз жүйеге сәтті кірдіңіз!",
  "toPay": "Төлеуге",
  "dineIn": "Мейрамханада",
  "takeaway": "Өзіңізбен бірге",
  "scanQR": "Бұл даяшыға тапсырысыңызды үстеліңізге әкелу үшін қажет",
  "addToOrder": "Тапсырысқа қосу",
  "gr": "гр",
  "anythingElse": "Тағы бірдеңе керек пе?",
  "selfPickupAt": "Мекенжай бойынша өзіңіз алып кету",
  "requiredField": "Міндетті жол",
  "wantToExit": "Шығуды қалайсыз ба?",
  "dishesWillRemoved": "Сіз тапсырысқа қосқан тағамдар себеттен жойылады.",
  "stay": "Қалу",
  "table": "Үстел",
  "congratulationsPrime": "Сіз енді Prime жазылушысыз!",
  "congratulationsPrimeDescription": "Құттықтаймыз! Кешбэк пен адалдық бағдарламасының артықшылықтары енді сізге қолжетімді",
  "gram100": "тағамның 100 грамына",
  "dish": "тағам",
  "payment": "Төлеу",
  "networkError": "Желі қатесі",
  "networkErrorDescription": "Тұрақсыз қосылу. Қайталап көріңіз",
  "minCountSubscription": "Рұқсат етілген акциядағы тауар саны 1",
  "noInternetConnection": "Интернет байланысы жоқ",
  "checkConnection": "Байланысты тексеріп, әрекетті қайталаңыз",
  "payWith": "Төлем әдісі",
  "continueOrder": "Заказды жалғастырғыңыз келе ме?",
  "yes": "Иә",
  "no": "Жоқ",
  "paymentTitle": "Тапсырысты төлеу",
  "cancelPurchaseButton": "Сатып алуды болдырмау",
  "tryAgainButton": "Қайтадан көру",
  "preparingToAcceptPayment": "Төлемді қабылдауға дайындалып жатырмыз",
  "scanAndPay": "Сканерлеп төлеңіз",
  "paymentMethods": "Төлем тәсілдері",
  "purchaseCancellationTitle": "Сатып алуды болдырмау",
  "youDidNotConfirm": "Сіз растаған жоқсыз",
  "paymentAccepted": "Төлем қабылданды",
  "enterYourName": "Біз сізді атыңызбен шақырамыз",
  "yourName": "Сіздің атыңыз",
  "nameRequired": "Бұл сіздің тапсырысыңыздың жоғалып кетпеуі үшін қажет. Сіз лақап атты пайдалана аласыз.",
  "yourOrderNumber": "Сіздің тапсырыс нөміріңіз",
  "scanAndPayDescription": "Ыңғайлы болу үшін суретке түсіріп, тапсырысыңызды алу аймағына өтіңіз",
  "checkWithOrder": "Чекті тапсырысыңызбен бірге аласыз",
  "recommend": "Ұсынамыз",
  "minimumOptions": "минимум таңдау керек",
  "options": "опцияны",
  "maximumOptions": "максимум таңдауга болады"
};
static const Map<String,dynamic> _ru_RU = {
  "selectCity": "Выберите город",
  "allCities": "Все города",
  "readMore": "Подробнее",
  "youCanGetFreeDrink": "Вам доступен бесплатный напиток!",
  "establishments": "Заведения",
  "stock": "Акции",
  "toTheRestaurantPage": "На страницу ресторана",
  "viewMenu": "Посмотреть меню",
  "addressContacts": "Адрес и контакты",
  "allDay": "Круглосуточно",
  "description": "Описание",
  "profile": "Профиль",
  "myDetails": "Мои данные",
  "orderHistory": "История заказов",
  "paymentMethod": "Способ оплаты",
  "notifications": "Уведомления",
  "support": "Поддержка",
  "language": "Язык",
  "logOut": "Выйти",
  "bonuses": "бонусов",
  "cashback": "Кешбэк",
  "myBonuses": "Мои бонусы",
  "cashbackInPoints": "Кешбэк в баллах",
  "pointsAccumulated": "Накоплено бонусов",
  "bonusHistory": "История бонусов",
  "howToSpendBonuses": "Как потратить бонусы?",
  "howToSpendBonusesDescription": "Заказывайте любимые блюда в ресторанах Sandyq или кофейнях Tary и оплачивайте через приложение Sandyq Prime.\nПри оплате выберите, сколько бонусов хотите потратить — бонусы могут покрыть до 50% вашего заказа.",
  "itsOkay": "Понятно",
  "points": "бонусы",
  "name": "Имя",
  "telephone": "Телефон",
  "dateOfBirth": "Дата рождения",
  "saveChanges": "Сохранить изменения",
  "deleteAccount": "Удалить аккаунт",
  "delete": "Удалить",
  "cancel": "Отмена",
  "privacyPolicy": "Политика конфиденциальности",
  "sandyqPrimePublicAgreement": "Публичный договор",
  "total": "Итого",
  "bonusesUpper": "Бонусы",
  "myCards": "Мои карты",
  "addCards": "Добавить карту",
  "thereIsNothingHereYet": "Здесь пока ничего нет",
  "nothingHereYetDescription": "Когда Вы получите уведомление, оно появится здесь",
  "howCanWeHelpYou": "Чем мы можем помочь?",
  "textOfTheAppeal": "Текст обращения",
  "describeTheProblemQuestion": "Опишите проблему или задайте вопрос",
  "additionally": "Дополнительно",
  "uploadFile": "Загрузить файл",
  "send": "Отправить",
  "areYouAtTaryCoffee": "Вы находитесь в кофейне Tary?",
  "taryCoffeeDescription1": "Чтобы заказать напиток с собой, отсканируйте QR-код у стойки бара",
  "taryCoffeeDescription2": "Чтобы насладиться напитком в зале, отсканируйте QR-код в табличке на столике",
  "scanQRcode": "Сканировать QR-код",
  "scanQrTable": "Отсканируйте QR на столе",
  "scanQRcodeDescription": "Наведите камеру на QR-код, чтобы заказать или оплатить",
  "close": "Закрыть",
  "chooseFreeDrink": "Выберите бесплатный напиток",
  "choose": "Выбрать",
  "order": "Заказать",
  "yourOrder": "Ваш заказ",
  "date": "Дата",
  "restaurantAddress": "Адрес ресторана",
  "orderAmount": "Сумма заказа",
  "service": "Обслуживание",
  "placeAnOrder": "Сделать заказ",
  "totalPrice": "Всего",
  "workingHours": "Время работы:",
  "main": "Главная",
  "drinkWaiting": "Напиток ждет вас",
  "drinkReceived": "Напиток сегодня получен",
  "comeBackTomorrow": "Возвращайтесь за новым завтра!",
  "getFreeDrink": "Вам доступен бесплатный напиток!",
  "balance": "Баланс",
  "subscriptionInformation": "Информация о подписке",
  "subscription": "Подписка",
  "active": "Активна",
  "benefitsAvailable": "Вам доступны все преимущества",
  "subscriptionActive": "Подписка активна",
  "nextPaymentDate": "Дата следующего платежа",
  "about": "О продукте",
  "enterName": "Введите имя",
  "enterPhone": "Введите телефон",
  "dateFormat": "дд.мм.гггг",
  "deleteAccountQuestion": "Вы уверены, что хотите удалить аккаунт?",
  "status": "Статус",
  "freeDrink": "Бесплатный напиток",
  "exitAccount": "Выйти из аккаунта?",
  "noBillsPay": "Нет счетов к оплате",
  "dishesOrder": "Блюда в заказе",
  "login": "Войти",
  "youSelectOptions": "Необходимо выбрать опции: 1 (Обязательно)",
  "learnMore": "Узнать больше",
  "issued": "Оформлена",
  "arrange": "Оформить",
  "authorization": "Авторизация",
  "yourPhoneNumber": "Ваш номер телефона",
  "getPinCode": "Получить код",
  "agreeTerms": "Я согласен с условиями",
  "userAgreement": "Пользовательского соглашения",
  "publicContract": "Публичного договора",
  "enterPinCode": "Код из СМС",
  "sentCodeNumber": "Мы отправили код на номер",
  "cont": "Продолжить",
  "referralProgram": "Реферальная программа",
  "reservations": "Бронирования",
  "bonusesForFriend": "+1 000 бонусов вам и другу",
  "sendBonuses": "Начислим вам и вашему другу по 1 000 бонусов, после его первой оплаты в приложении",
  "sharePromoCode": "Поделиться промокодом",
  "refProgramConditions": "Правила и условия реферальной программы",
  "bookingDetails": "Детали бронирования",
  "reservationNumber": "Номер брони",
  "time": "Время",
  "numberOfGuests": "Количество гостей",
  "commentForTheRestaurant": "Комментарий для ресторана",
  "cancelBooking": "Отменить бронирование",
  "booking": "Бронирование",
  "bookTable": "Забронировать стол",
  "man": "чел.",
  "moreThanSix": "Больше 6",
  "dateOfVisit": "Дата посещения",
  "visitingime": "Время посещения",
  "readyToBook": "Забронировать?",
  "bookNow": "Забронировать",
  "forExample": "Например: «Проведу в заведении 8 часов», или «Нужны детские стульчики»...",
  "tableReserved": "Столик забронирован",
  "restaurantWillContact": "Ресторан свяжется с вами, если по брони возникнут вопросы",
  "promocodeCopied": "Промокод скопирован, поделитесь им с другом!",
  "freeDrinkWithSubscription": "Бесплатный напиток по подписке",
  "freedrinksCashback": "Бесплатные напитки и кешбек 8%",
  "aboutCompany": "Сеть Ресторанов «Chayla Group» — компания, которая уже на рынке 5 лет, на данный момент в сеть входят 12 проектов.Основной вид деятельности: Деятельность ресторанов и предоставление услуг по доставке продуктов питания",
  "subscribeNow": "Оформить подписку",
  "greatOffer": "Cкидка 15%",
  "coffeLimit": "Вы сегодня уже воспользовались своим бесплатным напитком",
  "youCancelledSubscription": "Вы отменили подписку",
  "subscriptionPaidup": "Подписка оплачена до ",
  "afterThisPeriod": "после этого периода доступ ко всем привилегиям PRIME завершится",
  "cancelSubscription": "Отменить подписку",
  "accessWillEnd": "Доступ к бесплатным напиткам, повышенному кешбеку и подаркам завершится по окончании оплаченного периода",
  "yesCancel": "Да, отменить",
  "noLeaveIt": "Нет, оставить",
  "subscriptionCanceled": "Подписка отменена",
  "thanksForUsingPrime": "Спасибо, что использовали Prime! Вы всегда можете подписаться снова, чтобы восстановить свои привилегии.",
  "workingTime": "Режим работы",
  "location": "Местоположение",
  "success": "Изменения сохранены",
  "closed": "Закрыт",
  "invoiceFrom": "Счет от",
  "orderNumber": "Номер заказа",
  "requestSent": "Обращение отправлено",
  "requestSentDesc": "Спасибо, что сообщили нам о проблеме!",
  "save": "Сохранить",
  "bonusesHere": "Здесь будут ваши бонусы",
  "bonusesHereDesc": "Оплачивайте заказы в приложении\nи получайте до 8% кешбэка",
  "ordersHere": "Здесь будут ваши заказы",
  "ordersHereDesc": "Оплачивайте заказы в приложении и получайте до 8% кешбэка",
  "pay": "Перейти к оплате",
  "orderAccepted": "Заказ принят!",
  "paymentSuccessful": "Оплата прошла успешно",
  "freeDrinkSuccess": "Сотрудник принесёт напиток к месту заказа, как только он будет готов",
  "orderPaySuccess": "Поздравляем! Ваш заказ оплачен",
  "selectPaymentMethod": "Выберите способ оплаты",
  "spend": "Потратить",
  "spendDescFirst": "Можно оплачивать до",
  "spendDescSecond": "счета",
  "hasPromoCode": "Есть промокод?",
  "addBonus": "Начислим бонусов",
  "accumulateBonuses": "Накопим бонусов",
  "apply": "Применить",
  "enterPromo": "Введите промокод",
  "feedbackSent": "Отзыв отправлен, спасибо за уделённое время!",
  "commentOptional": "Комментарий (необязательно)",
  "rateVisitSandyq": "Оцените свой сегодняшний визит",
  "howDidItGo": "Как всё прошло?",
  "site": "Сайт",
  "paymentByQR": "Оплата по QR",
  "gender": "Пол",
  "selectGender": "Выберите пол",
  "enterEmail": "Введите email",
  "themale": "Мужской",
  "thefemale": "Женский",
  "successSubscriptionPay": "Поздравляем! Ваша подписка оформлено",
  "enterCorrectFormat": "Укажите правильный формат даты",
  "qrNotFound": "QR-код не найден",
  "qrNotFoundDesc": "Попробуйте снова, используя код от заведения, или обратитесь за помощью к сотруднику",
  "whatDoYouWantToDo": "Что вы хотите сделать?",
  "payOrder": "Оплатить заказ",
  "getAFreeDrink": "Получить бесплатный напиток",
  "upgradeRequired": "Необходимо обновить приложение",
  "upgrade": "Обновить",
  "more": "Больше",
  "additionalRequests": "Проверьте детали, сообщите ресторану, если есть дополнительные пожелания",
  "forExampleAdditional": "Например: «Проведу в заведении несколько часов», или «Нужны детские стульчики»...",
  "bookingError": "Ошибка бронирования",
  "pleaseTryAgain": "Пожалуйста, попробуйте еще раз. Если ошибка повторится – свяжитесь с рестораном.",
  "detailsNeeded": "Нужно уточнить детали",
  "additionalInformationRestaurant": "Нам нужна дополнительная информация, чтобы подготовиться к визиту большой компании. Пожалуйста, свяжитесь с рестораном.",
  "call": "Позвонить",
  "bookingNumber": "Номер стола",
  "cancelReservationQuestion": "Отменить бронирование?",
  "canceled": "Бронирование отменено",
  "back": "Назад",
  "noFreeSlots": "В этот день нет свободных слотов для бронирования",
  "noActive": "Активных броней нет",
  "noActiveDesc": "Вы можете забронировать визит заранее на странице ресторана",
  "orderError": "Заказ с ошибкой",
  "newOrder": "Новый заказ",
  "checkRequested": "Запросили чек",
  "closedStatus": "Закрыто",
  "inProcessing": "В обработке",
  "remoteOrder": "Удаленный заказ",
  "accepted": "Принято",
  "canceledStatus": "Отменено",
  "bonusesAccrued": "Начислено бонусов",
  "leaveFeedback": "Оставить отзыв",
  "drinkGift": "Напиток в подарок",
  "congratulations": "Поздравляем!",
  "successfullyLogged": "Мы рады, что вы с нами! Копите бонусы, просматривайте меню и заказывайте любимые блюда в два клика.",
  "supplements": "Добавки",
  "toPay": "К оплате",
  "dineIn": "В ресторане",
  "takeaway": "С собой",
  "scanQR": "Это нужно, чтобы официант принёс заказ за ваш стол",
  "addToOrder": "Добавить",
  "gr": "гр",
  "anythingElse": "Что-нибудь еще?",
  "selfPickupAt": "Самовывоз по адресу",
  "requiredField": "Обязательное поле",
  "wantToExit": "Вы уверены, что хотите выйти?",
  "dishesWillRemoved": "Блюда, которые вы добавили в заказ, будут удалены из корзины",
  "stay": "Остаться",
  "table": "Стол",
  "congratulationsPrime": "Вы теперь в подписке Prime!",
  "congratulationsPrimeDescription": "Поздравляем! Вам теперь доступны повышенный кешбэк и привилегии программы лояльности",
  "gram100": "на 100 гр. блюда",
  "dish": "блюда за",
  "payment": "Оплатить",
  "networkError": "Ошибка сети",
  "networkErrorDescription": "Нестабильное подключение. Попробуйте ещё раз",
  "minCountSubscription": "Допустимое количество акционных товаров 1",
  "noInternetConnection": "Нет подключения к Интернету",
  "checkConnection": "Проверьте подключение и попробуйте снова",
  "payWith": "Оплатить с",
  "continueOrder": "Хотите продолжить заказ?",
  "yes": "Да",
  "no": "Нет",
  "paymentTitle": "Оплата заказа",
  "cancelPurchaseButton": "Отменить покупку",
  "tryAgainButton": "Попробовать снова",
  "preparingToAcceptPayment": "Готовимся к приему оплаты",
  "scanAndPay": "Сканируйте и платите",
  "paymentMethods": "Способы оплаты",
  "purchaseCancellationTitle": "Отмена покупки",
  "youDidNotConfirm": "Вы не подтвердили",
  "paymentAccepted": "Оплата принята",
  "enterYourName": "Позовём вас по имени",
  "yourName": "Ваше имя",
  "nameRequired": "Это нужно, чтобы ваш заказ не потерялся. Можете использовать никнейм.",
  "yourOrderNumber": "Ваш номер заказа",
  "scanAndPayDescription": "Сделайте фото для удобства и пройдите в зону выдачи за своим заказом",
  "checkWithOrder": "Чек вы получите вместе с заказом",
  "recommend": "Рекомендуем",
  "minimumOptions": "выберите минимум",
  "options": "опций",
  "maximumOptions": "можно выбрать максимум"
};
static const Map<String,dynamic> _en_US = {
  "selectCity": "Select a city",
  "allCities": "All cities",
  "readMore": "More details",
  "youCanGetFreeDrink": "Redeem your free drink!",
  "establishments": "Locations",
  "stock": "Promotions",
  "toTheRestaurantPage": "To the restaurant's page",
  "viewMenu": "View menu",
  "addressContacts": "Address and info",
  "allDay": "Around the clock",
  "description": "Description",
  "profile": "Profile",
  "myDetails": "My data",
  "orderHistory": "Order history",
  "paymentMethod": "Payment method",
  "notifications": "Notifications",
  "support": "Support",
  "language": "Language",
  "logOut": "Log out",
  "bonuses": "bonuses",
  "cashback": "Cashback",
  "myBonuses": "My Bonuses",
  "cashbackInPoints": "Cashback in points",
  "pointsAccumulated": "Points accumulated",
  "bonusHistory": "Bonus History",
  "howToSpendBonuses": "How do I spend bonuses?",
  "howToSpendBonusesDescription": "Order your favorite dishes at Sandyq restaurants or Tary coffee shops and pay via the Sandyq Prime app. When paying, choose how many bonuses you want to spend — bonuses can cover up to 50% of your order.",
  "itsOkay": "Clear",
  "points": "points",
  "name": "Name",
  "telephone": "Telephone",
  "dateOfBirth": "Date of birth",
  "saveChanges": "Save changes",
  "deleteAccount": "Delete account",
  "delete": "Remove",
  "cancel": "Cancel",
  "privacyPolicy": "Privacy policy",
  "sandyqPrimePublicAgreement": "Public contract",
  "total": "Total",
  "bonusesUpper": "Bonuses",
  "myCards": "My cards",
  "addCards": "Add a card",
  "thereIsNothingHereYet": "There's nothing here yet",
  "nothingHereYetDescription": "Your notifications will be stored here",
  "howCanWeHelpYou": "How can we help you?",
  "textOfTheAppeal": "Appeal text",
  "describeTheProblemQuestion": "Describe your problem or ask a question",
  "additionally": "Additionally",
  "uploadFile": "Upload a file",
  "send": "Send",
  "areYouAtTaryCoffee": "Are you at the Tary Coffee Shop?",
  "taryCoffeeDescription1": "To order a drink to go, scan the QR code at the bar",
  "taryCoffeeDescription2": "To enjoy a drink in the establishment, scan the QR code on the table",
  "scanQRcode": "Scan the QR code",
  "scanQrTable": "Scan the QR code on the table",
  "scanQRcodeDescription": "Point the camera at the QR code to order or pay",
  "close": "Close",
  "chooseFreeDrink": "Choose a free drink",
  "choose": "Choose",
  "order": "Order",
  "yourOrder": "Your order",
  "date": "Date",
  "restaurantAddress": "Restaurant address",
  "orderAmount": "Order amount",
  "service": "Service",
  "placeAnOrder": "Place an order",
  "totalPrice": "Total",
  "workingHours": "Working hours:",
  "main": "Main",
  "drinkWaiting": "Redeem your free drink",
  "drinkReceived": "The drink was received today",
  "comeBackTomorrow": "Come back for more tomorrow!",
  "getFreeDrink": "You can get a free drink!",
  "balance": "Balance",
  "subscriptionInformation": "Subscription information",
  "subscription": "Subscription",
  "active": "Active",
  "benefitsAvailable": "All the benefits are available to you",
  "subscriptionActive": "Subscription is active",
  "nextPaymentDate": "Next payment date",
  "about": "About",
  "enterName": "Enter your name",
  "enterPhone": "Enter your phone number",
  "dateFormat": "dd.mm.yyyy",
  "deleteAccountQuestion": "Are you sure you want to delete your account?",
  "status": "Status",
  "freeDrink": "Free drink",
  "exitAccount": "Log out of the account?",
  "noBillsPay": "Bill not found",
  "dishesOrder": "Order contents",
  "login": "Log in",
  "youSelectOptions": "Required to pick 1 option",
  "learnMore": "Learn more",
  "issued": "Issued",
  "arrange": "Arrange",
  "authorization": "Authorization",
  "yourPhoneNumber": "Your phone number",
  "getPinCode": "Get code",
  "agreeTerms": "I agree to the terms",
  "userAgreement": "User Agreement",
  "publicContract": "Public contract",
  "enterPinCode": "Enter the code",
  "sentCodeNumber": "We sent the code to the number",
  "cont": "Continue",
  "referralProgram": "Referral program",
  "reservations": "Reservations",
  "bonusesForFriend": "+1,000 bonuses for you and your friend",
  "sendBonuses": "You and a friend that you refer will get 1000 bonuses after their first payment in the app",
  "sharePromoCode": "Share promo code",
  "refProgramConditions": "Referral Program Terms and Conditions",
  "bookingDetails": "Booking details",
  "reservationNumber": "Reservation number",
  "time": "Time",
  "numberOfGuests": "Number of guests",
  "commentForTheRestaurant": "Additional comment for the restaurant",
  "cancelBooking": "Cancel booking",
  "booking": "Booking",
  "bookTable": "Book a table",
  "man": "man.",
  "moreThanSix": "More than 6",
  "dateOfVisit": "Date of visit",
  "visitingime": "Visit time",
  "readyToBook": "Ready to book?",
  "bookNow": "Book now",
  "forExample": "For example: “I want to spend several hours in the establishment”, or “I need high chairs for a child”",
  "tableReserved": "Table reserved",
  "restaurantWillContact": "The restaurant will contact you if there are any questions regarding your reservation.",
  "promocodeCopied": "Promo code has been copied, share it with a friend!",
  "freeDrinkWithSubscription": "Free drink with subscription",
  "freedrinksCashback": "Free drinks and 8% cashback",
  "aboutCompany": "Restaurant chain 'Chayla Group' is a company that has been on the market for 5 years, currently the chain includes 12 projects. Main activity: Restaurant activities and provision of food delivery services",
  "subscribeNow": "Subscribe now",
  "greatOffer": "15% discount",
  "coffeLimit": "You've already redeemed your free drink today.",
  "youCancelledSubscription": "Your subscription was cancelled.",
  "subscriptionPaidup": "Subscription paid up to",
  "afterThisPeriod": "after this period, access to all PRIME privileges will end.",
  "cancelSubscription": "Cancel subscription",
  "accessWillEnd": "Access to free drinks, increased cashback and gifts will end at the end of the paid period",
  "yesCancel": "Yes, cancel",
  "noLeaveIt": "No, leave it",
  "subscriptionCanceled": "Subscription canceled",
  "thanksForUsingPrime": "Thanks for using Prime! You can always sign up again to restore your benefits.",
  "workingTime": "Working hours",
  "location": "Location",
  "success": "Success!",
  "closed": "Closed",
  "invoiceFrom": "Invoice from",
  "orderNumber": "Order number",
  "requestSent": "Your request has been sent",
  "requestSentDesc": "Thank you for letting us know about the problem!",
  "save": "Save",
  "bonusesHere": "Your bonuses will be stored here",
  "bonusesHereDesc": "Pay for your orders with the app\nand get up to 8% cashback",
  "ordersHere": "Your orders will be stored here",
  "ordersHereDesc": "Pay for your orders with the app and get up to 8% cashback",
  "pay": "Proceed to payment",
  "orderAccepted": "Order accepted!",
  "paymentSuccessful": "Payment was successful",
  "freeDrinkSuccess": "The employee will bring the drink to the place of order as soon as it is ready",
  "orderPaySuccess": "Congratulations! Your order has been paid",
  "selectPaymentMethod": "Select payment method",
  "spend": "Spend",
  "spendDescFirst": "You can pay up to",
  "spendDescSecond": "of the bill",
  "hasPromoCode": "Do you have a promo code?",
  "addBonus": "You will be awarded bonuses",
  "accumulateBonuses": "You will accumulate bonuses",
  "apply": "Apply",
  "enterPromo": "Enter promo code",
  "feedbackSent": "Feedback sent, thank you for your time!",
  "commentOptional": "Comment (optional)",
  "rateVisitSandyq": "Share your impressions!",
  "howDidItGo": "How did it go?",
  "site": "Site",
  "paymentByQR": "Payment by QR",
  "gender": "Gender",
  "selectGender": "Select gender",
  "enterEmail": "Enter email",
  "themale": "Male",
  "thefemale": "Female",
  "successSubscriptionPay": "Congratulations! Your subscription is complete.",
  "enterCorrectFormat": "Please enter the correct date format",
  "qrNotFound": "Qr code not found",
  "qrNotFoundDesc": "Please try again using the code provided by the establishment or ask a member of staff for assistance.",
  "whatDoYouWantToDo": "What do you want to do?",
  "payOrder": "Pay for the order",
  "getAFreeDrink": "Get a free drink",
  "upgradeRequired": "Upgrade required",
  "upgrade": "Upgrade",
  "more": "More",
  "additionalRequests": "Check the details and inform the restaurant if you have additional requests",
  "forExampleAdditional": "For example: “I want to stay for several hours,” or “We need high chairs for children.”",
  "bookingError": "Booking error",
  "pleaseTryAgain": "Please try again. If the error persists, contact the restaurant.",
  "detailsNeeded": "Details needed",
  "additionalInformationRestaurant": "We need additional information to prepare for your large group. Please contact the restaurant.",
  "call": "Call",
  "bookingNumber": "Booking number",
  "cancelReservationQuestion": "Cancel reservation?",
  "canceled": "Canceled",
  "back": "Back",
  "noFreeSlots": "There are no available slots for booking on this day.",
  "noActive": "No active bookings",
  "noActiveDesc": "You can book your visit in advance on the restaurant's page",
  "orderError": "Order with error",
  "newOrder": "New order",
  "checkRequested": "Check requested",
  "closedStatus": "Closed",
  "inProcessing": "In processing",
  "remoteOrder": "Order deleted",
  "accepted": "Accepted",
  "canceledStatus": "Canceled",
  "bonusesAccrued": "Bonuses accrued",
  "leaveFeedback": "Leave Feedback",
  "drinkGift": "Drink as a gift",
  "congratulations": "Congratulations!",
  "successfullyLogged": "You have successfully logged in!",
  "toPay": "To Pay",
  "dineIn": "Dine-in",
  "takeaway": "Takeaway",
  "scanQR": "This is necessary for the waiter to bring your order to your table.",
  "addToOrder": "Add to order",
  "gr": "gr",
  "anythingElse": "Anything else?",
  "selfPickupAt": "Self pickup at",
  "requiredField": "Required field",
  "wantToExit?": "Are you sure you want to exit?",
  "dishesWillRemoved": "The dishes you added to your order will be removed",
  "stay": "Stay",
  "table": "Table",
  "congratulationsPrime": "You are now a Prime subscriber!",
  "congratulationsPrimeDescription": "Congratulations! Increased cashback and loyalty program privileges are now available to you",
  "gram100": "per 100 gr. of the dish",
  "dish": "dishes for",
  "payment": "Pay",
  "networkError": "Network error",
  "networkErrorDescription": "Unstable connection. Try again.",
  "minCountSubscription": "The maximum number of promotional items is 1",
  "noInternetConnection": "No internet connection",
  "checkConnection": "Check your connection and try again",
  "payWith": "Pay with",
  "continueOrder": "Do you want to continue the order?",
  "yes": "Yes",
  "no": "No",
  "paymentTitle": "Order payment",
  "cancelPurchaseButton": "Cancel purchase",
  "tryAgainButton": "Try again",
  "preparingToAcceptPayment": "Preparing to accept payment",
  "scanAndPay": "Scan and pay",
  "paymentMethods": "Payment methods",
  "purchaseCancellationTitle": "Purchase cancellation",
  "youDidNotConfirm": "You did not confirm",
  "paymentAccepted": "Payment accepted",
  "enterYourName": "We'll call you by name",
  "yourName": "Your name",
  "nameRequired": "This is needed so that your order doesn't get lost. You can use a nickname.",
  "yourOrderNumber": "Your order number",
  "scanAndPayDescription": "Take a photo for convenience and proceed to the pickup area for your order",
  "checkWithOrder": "You will receive the receipt together with your order",
  "recommend": "Recommend",
  "minimumOptions": "select minimum",
  "options": "options",
  "maximumOptions": "select maximum"
};
static const Map<String, Map<String,dynamic>> mapLocales = {"kk_KK": _kk_KK, "ru_RU": _ru_RU, "en_US": _en_US};
}
